splcc – splpak
splcc Subroutine
19 statements
Source File
private subroutine splcc(me, ndim, xdata, l1xdat, ydata, ndata, xmin, xmax, nodes, xtrap, coef, ncf, work, nwrk, ierror)
N-dimensional cubic spline coefficient calculation by least squares.
The usage and arguments of this routine are identical to those for SPLCW except for the omission of the array of weights, WDATA. See entry SPLCW description for a complete description.
Type Bound
splpak_type
Arguments
Type Intent Optional Attributes Name
class(splpak_type), intent(inout) :: me
integer, intent(in) :: ndim
real(kind=wp), intent(in) :: xdata(l1xdat,ndata)
integer, intent(in) :: l1xdat
real(kind=wp), intent(in) :: ydata(ndata)
integer, intent(in) :: ndata
real(kind=wp), intent(in) :: xmin(ndim)
real(kind=wp), intent(in) :: xmax(ndim)
integer, intent(in) :: nodes(ndim)
real(kind=wp), intent(in) :: xtrap
real(kind=wp), intent(out) :: coef(ncf)
integer, intent(in) :: ncf
real(kind=wp) :: work(nwrk)
integer, intent(in) :: nwrk
integer, intent(out) :: ierror
Calls
Source Code
subroutine splcc(me,ndim,xdata,l1xdat,ydata,ndata,xmin,xmax,nodes, &
                 xtrap,coef,ncf,work,nwrk,ierror)
    class(splpak_type),intent(inout) :: me
    integer,intent(in) :: ndim
    integer,intent(in) :: l1xdat
    integer,intent(in) :: ncf
    integer,intent(in) :: nwrk
    integer,intent(in) :: ndata
    real(wp),intent(in) :: xdata(l1xdat,ndata)
    real(wp),intent(in) :: ydata(ndata)
    real(wp),intent(in) :: xmin(ndim)
    real(wp),intent(in) :: xmax(ndim)
    real(wp),intent(in) :: xtrap
    integer,intent(in) :: nodes(ndim)
    real(wp) :: work(nwrk)
    real(wp),intent(out) :: coef(ncf)
    integer,intent(out) :: ierror
    real(wp),dimension(1),parameter :: wdata = -1.0_wp !! indicates to [[splcw]]
                                                       !! that weights are not used
    call me%splcw(ndim,xdata,l1xdat,ydata,wdata,ndata,xmin,xmax,&
                  nodes,xtrap,coef,ncf,work,nwrk,ierror)
end subroutine splcc
Call graph
splcc calls splcw
splcw calls bascmp, cfaerr, destroy_splpak, suprls
suprls calls cfaerr