splfe – splpak
splfe Function
14 statements
Source File
private function splfe(me, ndim, x, coef, xmin, xmax, nodes, ierror)
N-dimensional cubic spline function evaluation.
Except for lack of derivative capability, this function is identical to function splde in usage. The argument list is also identical except for the omission of nderiv.
See also
splde
Note
coef, xmin, xmax and nodes must be exactly retained from the call to splcc (or splcw).
Type Bound
splpak_type
Arguments
Type Intent Optional Attributes Name
class(splpak_type), intent(inout) :: me
integer, intent(in) :: ndim
real(kind=wp), intent(in) :: x(ndim)
real(kind=wp), intent(out) :: coef(*)
real(kind=wp), intent(in) :: xmin(ndim)
real(kind=wp), intent(in) :: xmax(ndim)
integer, intent(in) :: nodes(ndim)
integer, intent(out) :: ierror
Return Value real(kind=wp)
Calls
Source Code
function splfe(me,ndim,x,coef,xmin,xmax,nodes,ierror)
    class(splpak_type),intent(inout) :: me
    real(wp) :: splfe
    integer,intent(in) :: ndim
    real(wp),intent(in) :: x(ndim)
    real(wp),intent(out) :: coef(*)
    real(wp),intent(in) :: xmin(ndim)
    real(wp),intent(in) :: xmax(ndim)
    integer,intent(in) :: nodes(ndim)
    integer,intent(out) :: ierror
    integer,dimension(ndim) :: nderiv
    nderiv = 0
    splfe = me%splde(ndim,x,nderiv,coef,xmin,xmax,nodes,ierror)
end function splfe
Call graph
splfe calls splde
splde calls bascmp, cfaerr