suprls – splpak
suprls Subroutine
238 statements
Source File
public subroutine suprls(i, rowi, n, bi, a, nn, soln, err, ier)
Solve the overdetermined system of linear equations.
Arguments
Type Intent Optional Attributes Name
integer :: i
real(kind=wp) :: rowi(n)
integer, intent(in) :: n
real(kind=wp) :: bi
real(kind=wp) :: a(nn)
integer :: nn
real(kind=wp) :: soln(n)
real(kind=wp) :: err
integer :: ier
Calls
Called by
Contents
Source Code
suprls
Source Code
subroutine suprls(i,rowi,n,bi,a,nn,soln,err,ier)
    integer :: i
    integer :: nn
    integer,intent(in) :: n
    real(wp) :: rowi(n)
    real(wp) :: bi
    real(wp) :: a(nn)
    real(wp) :: soln(n)
    real(wp) :: err
    real(wp) :: errsum
    real(wp) :: s
    real(wp) :: temp
    real(wp) :: temp1
    real(wp) :: cn
    real(wp) :: sn
    integer :: ier
    integer :: iold,np1,l,ilast,il1,k,k1,nreq,j,ilj,ilnp,&
               isav,idiag,i1,i2,ii,jp1,lmkm1,j1,jdel,idj,iijd,&
               i1jd,k11,k1m1,i11,np1mk,lmk,imov,iii,iiim,iim1,&
               ilk,npk,ilii,npii
    logical :: complete_reduction !! Routine entered with `I<=0` means complete
                                  !! the reduction and store the solution in `SOLN`.
    real(wp),parameter :: tol = 1.0e-18_wp !! small number tolerance
    save
    ier = 0
    complete_reduction = i <= 0
    if (.not. complete_reduction) then
        if (i<=1) then
            !  Set up quantities on first call.
            iold = 0
            np1 = n + 1
            !  Compute how many rows can be input now.
            l = nn/np1
            ilast = 0
            il1 = 0
            k = 0
            k1 = 0
            errsum = 0.0_wp
            nreq = ((n+5)*n+2)/2
            !  Error exit if insufficient scratch storage provided.
            if (nn<nreq) then
                ier = 32
                write(*,*) 'nn   = ', nn
                write(*,*) 'nreq = ', nreq
                call cfaerr(ier, &
                            ' suprls - insufficient scratch storage provided. '//&
                            'at least ((N+5)*N+2)/2 locations needed')
                return
            end if
        end if
        !  Error exit if (I-IOLD)/=1.
        if ((i-iold)/=1) then
            ier = 35
            write(*,*) 'i    =',i
            write(*,*) 'iold =',iold
            call cfaerr(ier,' suprls - values of I not in sequence')
            return
        end if
        !  Store the row in the scratch storage.
        iold = i
        do j = 1,n
            ilj = ilast + j
            a(ilj) = rowi(j)
        end do
        ilnp = ilast + np1
        a(ilnp) = bi
        ilast = ilast + np1
        isav = i
        if (i<l) return
    end if
    main : do
        if (.not. complete_reduction) then
            if (k/=0) then
                k1 = min(k,n)
                idiag = -np1
                if (l-k==1) then
                    !  Apply rotations to zero out the single new row.
                    do j = 1,k1
                        idiag = idiag + (np1-j+2)
                        i1 = il1 + j
                        if (abs(a(i1))<=tol) then
                            s = sqrt(a(idiag)*a(idiag))
                        else if (abs(a(idiag))<tol) then
                            s = sqrt(a(i1)*a(i1))
                        else
                            s = sqrt(a(idiag)*a(idiag)+a(i1)*a(i1))
                        end if
                        if (s==0.0_wp) cycle
                        temp = a(idiag)
                        a(idiag) = s
                        s = 1.0_wp/s
                        cn = temp*s
                        sn = a(i1)*s
                        jp1 = j + 1
                        do j1 = jp1,np1
                            jdel = j1 - j
                            idj = idiag + jdel
                            temp = a(idj)
                            i1jd = i1 + jdel
                            a(idj) = cn*temp + sn*a(i1jd)
                            a(i1jd) = -sn*temp + cn*a(i1jd)
                        end do
                    end do
                else
                    !  Apply householder transformations to zero out new rows.
                    do j = 1,k1
                        idiag = idiag + (np1-j+2)
                        i1 = il1 + j
                        i2 = i1 + np1* (l-k-1)
                        s = a(idiag)*a(idiag)
                        do ii = i1,i2,np1
                            s = s + a(ii)*a(ii)
                        end do
                        if (s==0.0_wp) cycle
                        temp = a(idiag)
                        a(idiag) = sqrt(s)
                        if (temp>0.0_wp) a(idiag) = -a(idiag)
                        temp = temp - a(idiag)
                        temp1 = 1.0_wp / (temp*a(idiag))
                        jp1 = j + 1
                        do j1 = jp1,np1
                            jdel = j1 - j
                            idj = idiag + jdel
                            s = temp*a(idj)
                            do ii = i1,i2,np1
                                iijd = ii + jdel
                                s = s + a(ii)*a(iijd)
                            end do
                            s = s*temp1
                            a(idj) = a(idj) + s*temp
                            do ii = i1,i2,np1
                                iijd = ii + jdel
                                a(iijd) = a(iijd) + s*a(ii)
                            end do
                        end do
                    end do
                end if
                if (k>=n) then
                    lmkm1 = l - k
                    !  Accumulate residual sum of squares.
                    do ii = 1,lmkm1
                        ilnp = il1 + ii*np1
                        errsum = errsum + a(ilnp)*a(ilnp)
                    end do
                    if (i<=0) exit main
                    k = l
                    ilast = il1
                    !  Determine how many new rows may be input on next iteration.
                    l = k + (nn-ilast)/np1
                    return
                end if
            end if
            k11 = k1 + 1
            k1 = min(l,n)
            if (l-k/=1) then
                k1m1 = k1 - 1
                if (l>n) k1m1 = n
                i1 = il1 + k11 - np1 - 1
                !  Perform householder transformations to reduce rows to upper
                !  triangular form.
                do j = k11,k1m1
                    i1 = i1 + (np1+1)
                    i2 = i1 + (l-j)*np1
                    s = 0.0_wp
                    do ii = i1,i2,np1
                        s = s + a(ii)*a(ii)
                    end do
                    if (s==0.0_wp) cycle
                    temp = a(i1)
                    a(i1) = sqrt(s)
                    if (temp>0.0_wp) a(i1) = -a(i1)
                    temp = temp - a(i1)
                    temp1 = 1.0_wp/ (temp*a(i1))
                    jp1 = j + 1
                    i11 = i1 + np1
                    do j1 = jp1,np1
                        jdel = j1 - j
                        i1jd = i1 + jdel
                        s = temp*a(i1jd)
                        do ii = i11,i2,np1
                            iijd = ii + jdel
                            s = s + a(ii)*a(iijd)
                        end do
                        s = s*temp1
                        i1jd = i1 + jdel
                        a(i1jd) = a(i1jd) + s*temp
                        do ii = i11,i2,np1
                            iijd = ii + jdel
                            a(iijd) = a(iijd) + s*a(ii)
                        end do
                    end do
                end do
                if (l>n) then
                    np1mk = np1 - k
                    lmk = l - k
                    ! Accumulate residual sum of squares.
                    do ii = np1mk,lmk
                        ilnp = il1 + ii*np1
                        errsum = errsum + a(ilnp)*a(ilnp)
                    end do
                end if
            end if
            imov = 0
            i1 = il1 + k11 - np1 - 1
            !  Squeeze the unnecessary elements out of scratch storage to
            !  allow space for more rows.
            do ii = k11,k1
                imov = imov + (ii-1)
                i1 = i1 + np1 + 1
                i2 = i1 + np1 - ii
                do iii = i1,i2
                    iiim = iii - imov
                    a(iiim) = a(iii)
                end do
            end do
            ilast = i2 - imov
            il1 = ilast
            if (i<=0) exit main
            k = l
            !  Determine how many new rows may be input on next iteration.
            l = k + (nn-ilast)/np1
            return
        end if
        ! Complete reduction and store solution in SOLN.
        complete_reduction = .false. ! reset this flag
        l = isav
        ! Error exit if L less than N.
        if (l<n) then
            ier = 33
            call cfaerr(ier,' suprls - array has too few rows.')
            return
        end if
        ! K/=ISAV means further reduction needed.
        if (k==isav) exit main
    end do main
    ilast = (np1* (np1+1))/2 - 1
    if (a(ilast-1)==0.0_wp) then
        ! Error return if system is singular.
        ier = 34
        call cfaerr(ier,' suprls - system is singular.')
        return
    end if
    ! Solve triangular system into ROWI.
    soln(n) = a(ilast)/a(ilast-1)
    do ii = 2,n
        iim1 = ii - 1
        ilast = ilast - ii
        s = a(ilast)
        do k = 1,iim1
            ilk = ilast - k
            npk = np1 - k
            s = s - a(ilk)*soln(npk)
        end do
        ilii = ilast - ii
        if (a(ilii)==0.0_wp) then
            ! Error return if system is singular.
            ier = 34
            call cfaerr(ier,' suprls - system is singular.')
            return
        end if
        npii = np1 - ii
        soln(npii) = s/a(ilii)
    end do
    ! Store residual norm.
    err = sqrt(errsum)
end subroutine suprls
Call graph
suprls calls cfaerr
splcw calls suprls
splcc calls splcw